management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: postgres
    password: password


spring:
  profiles:
    active: dev
